### ISSUE TITLE
Fails to decode a sufficiently complex avro model

### ISSUE THREAD

**Issue by mphfish** [beam-community/avro_ex#11]
Hey, thanks for putting together this library!

We are using `AvroEx` to process messages sent over Kafka, and are running into some problems with a sufficiently complex avro model.

I've put together a small repo that isolates the issue we're running into here: https://github.com/mphfish/avro_ex_issue

Basically, what I've been able to isolate it down to, is what I think is an off-by-one error when you have an empty array that is behind nullable keys.  If there are items in the array (as in the third unit test in that repo), the decode process works just fine.  When we step through the code, `do_decode/3` seems to be processing the empty byte arrays an additional time.

We've forked the code internally, and by adding:

```elixir
  def do_decode(%Record{}, _context, <<0>>), do: {%{}, <<>>}
  def do_decode(%Record{}, _context, <<>>), do: {%{}, <<>>}

  def do_decode(%Record{} = record, %Context{} = context, data) when is_binary(data) do
```

We're able to get it to properly decode messages, but we end up putting either `%{}` or `<<>>` into the arrays.

Unsure if you might have any ideas why this issue is occurring, but I'm happy to try anything we can with a much more complex Avro model that I can't have out in public.

**Comment by doomspork** [comment]
@mphfish I'm going to be taking over the maintenance of the repo, could you check if this issue exists against the latest master?

**Comment by mphfish** [comment]
@doomspork Nice!  This was resolved by https://github.com/beam-community/avro_ex/pull/16 .

Glad to see some activity on this!

**Comment by doomspork** [comment]
@mphfish we'd love for you to stay involved with the project and help us continue to grow it!
