### ISSUE TITLE
Add ability to generate and Ecto Schema from an Avro Schema

### ISSUE THREAD

**Issue by CJPoll** [beam-community/avro_ex#17]
```elixir
defmodule MyType do
  use AvroEx.GeneratedSchema, file: "priv/avro_schemas/my_type.avsc"

  def changeset(_, _) do
    ...
  end
end
```

Alternatively, a mix task which generate `.ex` files from a `.avsc` file.

`mix avro.gen.schema priv/schemas/my_schema.avsc MyApp.Context.SomeFile`

**Comment by davydog187** [comment]
This is a neat idea, but I believe ultimately not that a direction that I think we should push users. Going to close. Please reopen if you feel strongly that its helpful
