### ISSUE TITLE
Latest version release

### ISSUE THREAD

**Issue by Strech** [beam-community/avro_ex#23]
Hey,
first of all thanks for a great project! I would like to request the latest master release as a package version because you did a great job and remove `Poison` dependency in favour of `Jason`.

I think it's a great improvement and I'm building a library based on this project, but unfortunately, I can't publish it with a dependency from git.

**UPD:** Do you plan to release stable?

Thanks ❤️

**Comment by Strech** [comment]
Just in case if someone interested – here is a shiny new Elixir library for working with Avro Schemas https://github.com/Strech/avrora

**Comment by doomspork** [comment]
@Strech sorry for some reason this never showed up in my GH notifications. I just happened to notice. For the record, editing your original message with an update does not trigger a notification to anyone. In the future if there isn't a response it's easiest to create a new reply and ping the org :+1: 

I'll cut a new release.

Best of luck with your library! We would have welcomed your contributions :+1:
