### ISSUE TITLE
Update release dependencies

### ISSUE THREAD

**Issue by Naillik1** [beam-community/avro_ex#25]
Hi - the current release (`avro_ex 0.1.0-beta.6`) has a dependency on `ecto 2.1.0 or 2.2.0`, but ecto is now on v3.2.5. My project depends on ecto 3.x - are there plans to make a release with updated dependencies soon?

**Comment by doomspork** [comment]
@Naillik1 we'd welcome a PR that updates the dependencies and ensures things function accordingly :+1:

**Comment by Naillik1** [comment]
@doomspork Are there plans to release this via hex any time soon? 
(ps, thanks for the quick turnaround!)

**Comment by colinsmetz** [comment]
Hey! From what I understand, the update of dependencies has been done in PR #26 and a new release was done on March 10, 2020 (and [pushed to Hex](https://hex.pm/packages/avro_ex)). So this issue should be closed, right?
