### ISSUE TITLE
Empty string for namespace makes `AvroEx.decode_schema/1` fail

### ISSUE THREAD

**Issue by jbruggem** [beam-community/avro_ex#79]
Hi,

Thank your for this amazing library !

I think I have found a small bug in the latest version of AvroEx: the empty string is not accepted as a valid value for a namespace, but I think that it should.

Indeed, while reading Avro's specification, it seems that an empty value is a valid value for the field `namespace` (emphasis is mine):

> A namespace is a dot-separated sequence of such names. **The empty string may also be used as a namespace** to indicate the null namespace. 

Here is a small reproducible example:

```elixir
Mix.install([{:avro_ex, "2.0.1"}])

schema = """
{
  "type": "record",
  "name": "something",
  "namespace": "",
  "fields" : [{"name": "count", "type": {"type": "string"}}]
}
"""

schema |> AvroEx.decode_schema() |> IO.inspect()
```

I get the following error: 

```
{:error,
 %AvroEx.Schema.DecodeError{
   message: "Invalid name `` for `namespace` in %{\"fields\" => [%{\"name\" => \"count\", \"type\" => %{\"type\" => \"string\"}}], \"name\" => \"something\", \"namespace\" => \"\", \"type\" => \"record\"}"
 }}
```

I stumbled upon this problem while trying to upgrade from AvroEx 1.2 to AvroEx 2.0.1.  The avro files I'm decoding are produced by Avro's Java implementation.

**Comment by davydog187** [comment]
Thank you for reporting, @jbruggem! Would you be interested in submitting a bugfix?

**Comment by jbruggem** [comment]
> Thank you for reporting, @jbruggem! Would you be interested in submitting a bugfix?

I can certainly give it a try :).
