### ISSUE TITLE
Expose AvroEx.Decode.decode

### ISSUE THREAD

**Issue by jbruggem** [beam-community/avro_ex#87]
`AvroEx.Decode.decode` is very useful to partially decode an avro binary, and keep the remaining bytes for further decoding using another schema. We use it to decode Avro OCF files.

Would it be possible to officially expose it as part of Avro's API, either directly or with a function like `AvroEx.decode_partial` ?

I can submit a PR if it helps !

**Comment by davydog187** [comment]
Its exposed via [AvroEx.decode/2](https://github.com/beam-community/avro_ex/blob/master/lib/avro_ex.ex#L184) and is just a thin wrapper around the internal module. Are you looking for something else?

**Comment by davydog187** [comment]
Please reopen if I'm missing something

**Comment by jbruggem** [comment]
Thanks for the reply @davydog187  ! 

What's missing (for me) if I use `AvroEx.decode` is that I can recover the remaining non-decoded bytes that `AvroEx.Decode.decode` returns. It returns  `{:ok, decoded_value, remaining_bytes}`, but `AvroEx.decode`  discards the third element of the tuple:

```elixir
 case AvroEx.Decode.decode(schema, message, opts) do
      {:ok, value, _} -> {:ok, value}
      {:error, error} -> {:error, error}
    end
```

We use those remaining bytes to decode an OCF file, where the header must be decoded first to extract schema information that is needed to decode the rest.

**Comment by davydog187** [comment]
@jbruggem what do you think about explicit support for decoding OCF files? We could have a separate API or an option for it as part of the `decode/3` API

**Comment by jbruggem** [comment]
> @jbruggem what do you think about explicit support for decoding OCF files? We could have a separate API or an option for it as part of the decode/3 API

That sounds like a good idea, but it's a lot more work than just adding a `AvroEx.decode_partial` function :). Shouldn't we treat those two question separately, since adding support for OCF will probably take some time ?

**Comment by davydog187** [comment]
I'm not in favor of adding an `AvroEx.decode_partial` function, as it makes the surface are of the `AvroEx` API harder to understand, I'm also not aware of other use cases other than OCF that require it

**Comment by davydog187** [comment]
On second thought, there is a PR in progress to decode OCF files https://github.com/beam-community/avro_ex/pull/81

**Comment by jbruggem** [comment]
> On second thought, there is a PR in progress to decode OCF files #81

Thanks for the info, I'll keep an eye on it.

**Comment by veedo** [comment]
@jbruggem - Have a look at AvroEx.ObjectContainer.decode_file.
I'm still busy testing it, but early feedback is always nice.
